apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-k10
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kasten.io/
    chart: k10
    targetRevision: 7.5.1
    helm:
      values: |
        gateway:
          service:
            type: NodePort
            nodePort: 30098
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
